### ISSUE TITLE
Removing individuals

### ISSUE THREAD

**Issue by thoree** [magnusdv/quickped#5]
I am not allowed to remove individuals 201, 202 and 203 in the pedigree below:
![image](https://user-images.githubusercontent.com/10831495/145428476-3129b78d-4700-4019-8989-e4e3636b1278.png)

**Comment by magnusdv** [comment]
Thanks, this is indeed a bug. The command `pedtools::removeIndividuals(x, ids)` which works behind the scenes here, is not very advanced: it removes `ids` *and all their descendants*. In your example that leaves an empty pedigree, hence the error message.

In general, the problem of removing individuals (so that the result is a proper pedigree) is surprisingly confusing. For a simple example, suppose you remove individual 203 in your example. What would you expect to happen? 

Here are 3 possibilities:
* Keep all the others, but loose the father-daughter connection between 201 and 102.
* Remove 201 as well, since he is a "single parent". Then 202 must also go (by the same argument), leaving only the bottom trio.
* Remove 203 and all her descendants (102 and 205), leaving the upper-left trio.

The last strategy, i.e., removing all descendants, is the one currently adopted by `removeIndividuals()`. 

As your example shows, the implementation clearly has room for improvement.

**Comment by magnusdv** [comment]
This feature was rewritten in QuickPed 3.0.0, splitting the "Remove individuals" in two:
* Up: Removes ancestors. In the example above this corresponds to the first of the three options.
* Down: Removes descendants, e.g., the third option.
